sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis-ci@design4.pro'
script:
  - npm run test:debug
  - npm run test:check-coverage
after_success:
  - npm run report-coverage
